name: recipeapp
description: "A new Flutter project."
# A linha a seguir impede que o pacote seja publicado acidentalmente no pub.dev usando `flutter pub publish`.
# Isso é preferível para pacotes privados.
publish_to: 'none' # Remova esta linha se desejar publicar no pub.dev

# A seguir define a versão e o número da compilação para sua aplicação.
# Um número de versão é composto por três números separados por pontos, como 1.2.43
# seguido por um número de compilação opcional separado por um +.
# Tanto o número da versão quanto o número da compilação podem ser substituídos no flutter
# build especificando --build-name e --build-number, respectivamente.
# No Android, build-name é usado como versionName enquanto build-number é usado como versionCode.
# Leia mais sobre a versionagem do Android em https://developer.android.com/studio/publish/versioning
# No iOS, build-name é usado como CFBundleShortVersionString enquanto build-number é usado como CFBundleVersion.
# Leia mais sobre a versionagem do iOS em
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# No Windows, build-name é usado como as partes major, minor e patch
# das versões do produto e do arquivo, enquanto build-number é usado como sufixo de compilação.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# As dependências especificam outros pacotes que seu pacote precisa para funcionar.
# Para atualizar automaticamente as dependências do seu pacote para as últimas versões
# considere executar `flutter pub upgrade --major-versions`. Alternativamente,
# as dependências podem ser atualizadas manualmente alterando os números de versão abaixo para
# a versão mais recente disponível no pub.dev. Para ver quais dependências têm novas
# versões disponíveis, execute `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: 1.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
